# Generated by Django 3.2.6 on 2021-08-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/blog')),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Heart'), ('Heart Disease', 'Heart Disease'), ('Covid 19', 'Covid 19'), ('Immunization', 'Immunization')], max_length=30)),
                ('summary', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/blog')),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Heart'), ('Heart Disease', 'Heart Disease'), ('Covid 19', 'Covid 19'), ('Immunization', 'Immunization')], max_length=30)),
                ('summary', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
